name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - "other/*"
      - ".gitignore"
      - "package.json"
      - "bunfig.toml"
      - "vite.config.js"
      # - "svgo.config.js"
      - "src/**"
      - ".github/workflows/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website to Netlify
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/5c23354f454e1350f8543e78
